package com.sysco.payplus.service.calculation.rules

import com.sysco.rps.service.calculation.fact.RouteFact;

global org.slf4j.Logger logger;

dialect "java"

rule "Calculate Stops Pay"
  salience -1
  agenda-group "Stops Pay"
    when
      stopsPay: RouteFact(perMinuteRate : getPerMinuteRate(), minutesPerStop: getMinutesPerStop(), stopCount: getStopCount())
    then
      logger.info("starting per stops pay calculation with per minute rate {}, minutes per stop {}, stop count {}", perMinuteRate, minutesPerStop, stopCount);
      stopsPay.setCalculatedValue(perMinuteRate * minutesPerStop * stopCount);
      logger.info("finished stops pay calculation with result {}", stopsPay.getCalculatedValue());
end
