version: 0.2

env:
  parameter-store:
    JFROG_API_KEY: "/CP/COMMON/JFROG/APIKEY"
  exported-variables:
    - JFROG_API_KEY

phases:
  pre_build:
    commands:
      - echo $JFROG_USER
      - echo $JFROG_PASS
      - chmod +x gradlew
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build -x test
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_BUILD_ID | sed -e "s/^reference-price-service-build://"
      - code_build_id=$(echo $CODEBUILD_BUILD_ID | sed -e "s/^reference-price-service-build://")
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$code_build_id .
      - docker tag $IMAGE_REPO_NAME:$code_build_id $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$code_build_id
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$code_build_id
