#!/bin/sh
# ###########################################################################
# Script generated by Fortify SCA Scan Wizard (c) 2011-2020 Micro Focus or one of its affiliates
# Created on 2020/05/03 17:46:32
# ###########################################################################
# Generated for the following languages:
# 	Java
# 	Java Bytecode
# 	SQL
# 	XML
# ###########################################################################
# DEBUG - if set to true, runs SCA in debug mode
# SOURCEANALYZER - the name of the SCA executable
# FPR - the name of analysis result file
# BUILDID - the SCA build id
# ARGFILE - the name of the argument file that's extracted and passed to SCA
# BYTECODE_ARGFILE - the name of the argument file for Java Bytecode translation that's extracted and passed to SCA
# MEMORY - the memory settings for SCA
# LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
# OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
# FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
# ###########################################################################

DEBUG=true
SOURCEANALYZER=sourceanalyzer
FPR="Fortifypayplus-api.fpr"
BUILDID="payplus-api"
ARGFILE="Fortifypayplus-api.sh.args"
BYTECODE_ARGFILE="Fortifypayplus-api.sh.bytecode.args"
MEMORY="-Xmx1961M -Xms400M -Xss24M "

LAUNCHERSWITCHES=""
OLDFILENUMBER=Fortifypayplus-api.sh.fileno
FILENOMAXDIFF=10
ENABLE_BYTECODE=false

PROJECTROOT0="."
if [ ! -d "$PROJECTROOT0" ]; then
   echo  "ERROR: This script is being run on a different machine than it was"
   echo  "       generated on or the targeted project has been moved. This script is "
   echo  "       configured to locate files at"
   echo  "          $PROJECTROOT0"
   echo  "       Please modify the \$PROJECTROOT0 variable found"
   echo  "       at the top of this script to point to the corresponding directory"
   echo  "       located on this machine."
   exit
fi

if [ $DEBUG = true ]; then export LAUNCHERSWITCHES="-debug $LAUNCHERSWITCHES"; fi
echo Extracting Arguments File


grep "# ARGS" $0 | grep -v grep | cut -d" " -f3- | sed -e s#PROJECTROOT0_MARKER#"$PROJECTROOT0"#g   > $ARGFILE

grep "# BYTECODE_ARGS" $0 | grep -v grep | cut -d" " -f3- | sed -e s#PROJECTROOT0_MARKER#"$PROJECTROOT0"#g   > $BYTECODE_ARGFILE

if [ -s $BYTECODE_ARGFILE ]; then
ENABLE_BYTECODE=true
fi
# ###########################################################################
echo Cleaning previous scan artifacts
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID -clean 
if [ $? -ne 0 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
# ###########################################################################
echo Translating files
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID @$ARGFILE
if [ $? -ne 0 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
# ###########################################################################
if [ $ENABLE_BYTECODE = true ]; then
echo Translating Java bytecode files
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID @$BYTECODE_ARGFILE
if [ $? -ne 0 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
fi
# ###########################################################################
echo Testing Difference between Translations
FILENUMBER=`$SOURCEANALYZER -b $BUILDID -show-files | wc -l`

if [ ! -f $OLDFILENUMBER ]; then
	echo It appears to be the first time running this script, setting $OLDFILENUMBER to $FILENUMBER
	echo $FILENUMBER > $OLDFILENUMBER
else
	OLDFILENO=`cat $OLDFILENUMBER`
	DIFF=`expr $OLDFILENO "*" $FILENOMAXDIFF`
	DIFF=`expr $DIFF /  100`

	MAX=`expr $OLDFILENO + $DIFF`
	MIN=`expr $OLDFILENO - $DIFF`

	if [ $FILENUMBER -lt $MIN ] ; then SHOWWARNING=true; fi
	if [ $FILENUMBER -gt $MAX ] ; then SHOWWARNING=true; fi

	if [ -n "$SHOWWARNING" ] && [ "$SHOWWARNING" = true ] ; then
		echo "WARNING: The number of files has changed by over $FILENOMAXDIFF%, it is recommended"
		echo "         that this script is regenerated with the ScanWizard"
	fi

	echo $MAX $MIN $DIFF
fi;

# ###########################################################################
echo Starting scan
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID -quick -scan -f $FPR
if [ $? -ne 0 ] ; then
echo Sourceanalzyer failed, exiting
exit
fi
# ###########################################################################
echo Finished
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/bin/test:PROJECTROOT0_MARKER/build/libs/payplus-api-0.0.1-SNAPSHOT.jar:PROJECTROOT0_MARKER/build/classes/java/main:PROJECTROOT0_MARKER/bin/main:PROJECTROOT0_MARKER/gradle/wrapper/gradle-wrapper.jar"
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/build/classes/java/test"
# ARGS "-source"
# ARGS "1.8"
# ARGS "-Dcom.fortify.sca.fileextensions.sql=PLSQL"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.jar"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.class"
# ARGS "PROJECTROOT0_MARKER"
