DROP ALL OBJECTS;

DROP SCHEMA IF EXISTS `REF_PRICE_020`;

CREATE SCHEMA IF NOT EXISTS `REF_PRICE_020`;
-- SET SCHEMA REF_PRICE_020;

DROP TABLE IF EXISTS `PRICE`;
CREATE TABLE IF NOT EXISTS `PRICE`
(
    `SUPC`            varchar(9) NOT NULL,
    `PRICE_ZONE`      int(1)     NOT NULL,
    `PRICE`           double(13) NOT NULL,
    `EFFECTIVE_DATE`  datetime   NOT NULL,
    `EXPORTED_DATE`   bigint(10) NOT NULL,
    `CATCH_WEIGHT_INDICATOR` char(1)    NOT NULL,
    PRIMARY KEY (`SUPC`, `PRICE_ZONE`, `EFFECTIVE_DATE`, `EXPORTED_DATE`)
--                       KEY `pa_ix_supc_pz_eff_date` (`SUPC`,`PRICE_ZONE`,`EFFECTIVE_DATE`)
);

DROP TABLE IF EXISTS `PRICE_ZONE_01`;
CREATE TABLE IF NOT EXISTS `PRICE_ZONE_01`
(

    `SUPC`           varchar(9)  NOT NULL,
    `PRICE_ZONE`     int(1)      NOT NULL,
    `CUSTOMER_ID`    varchar(14) NOT NULL,
    `EFFECTIVE_DATE` datetime    NOT NULL,
    PRIMARY KEY (`CUSTOMER_ID`, `SUPC`, `EFFECTIVE_DATE`)
);

DROP TABLE IF EXISTS `PRICE_ZONE_02`;
CREATE TABLE IF NOT EXISTS `PRICE_ZONE_02`
(
    `SUPC`           varchar(9)  NOT NULL,
    `PRICE_ZONE`     int(1)      NOT NULL,
    `CUSTOMER_ID`    varchar(14) NOT NULL,
    `EFFECTIVE_DATE` datetime    NOT NULL,
    PRIMARY KEY (`CUSTOMER_ID`, `SUPC`, `EFFECTIVE_DATE`)
);

DROP TABLE IF EXISTS `PRICE_ZONE_MASTER_DATA`;
CREATE TABLE IF NOT EXISTS `PRICE_ZONE_MASTER_DATA` (
	`TABLE_TYPE` varchar NOT NULL PRIMARY KEY,
	`TABLE_NAMES` varchar NOT NULL,
	`EFFECTIVE_DATE` DATETIME NOT NULL
);

INSERT INTO PRICE_ZONE_MASTER_DATA VALUES('ACTIVE', 'PRICE_ZONE_01', '2020-01-01');
INSERT INTO PRICE_ZONE_MASTER_DATA VALUES('HISTORY', 'PRICE_ZONE_02', '2019-01-01');
INSERT INTO PRICE_ZONE_MASTER_DATA VALUES('FUTURE', 'PRICE_ZONE_03', '2019-01-01');
