DROP ALL OBJECTS;

DROP SCHEMA IF EXISTS `REF_PRICE_020`;

CREATE SCHEMA IF NOT EXISTS `REF_PRICE_020`;
-- SET SCHEMA REF_PRICE_020;

DROP TABLE IF EXISTS `PA`;
CREATE TABLE IF NOT EXISTS `PA`
(
    `SUPC`            varchar(9) NOT NULL,
    `PRICE_ZONE`      int(1)     NOT NULL,
    `PRICE`           double(13) NOT NULL,
    `EFFECTIVE_DATE`  datetime   NOT NULL,
    `EXPORTED_DATE`   bigint(10) NOT NULL,
    `SPLIT_INDICATOR` char(1)    NOT NULL,
    PRIMARY KEY (`SUPC`, `PRICE_ZONE`, `EFFECTIVE_DATE`, `EXPORTED_DATE`)
--                       KEY `pa_ix_supc_pz_eff_date` (`SUPC`,`PRICE_ZONE`,`EFFECTIVE_DATE`)
);

DROP TABLE IF EXISTS `PRICE_ZONE_01`;
CREATE TABLE IF NOT EXISTS `PRICE_ZONE_01`
(

    `SUPC`           varchar(9)  NOT NULL,
    `PRICE_ZONE`     int(1)      NOT NULL,
    `CUSTOMER_ID`    varchar(14) NOT NULL,
    `EFFECTIVE_DATE` datetime    NOT NULL,
    PRIMARY KEY (`CUSTOMER_ID`, `SUPC`)
);

-- TRUNCATE TABLE `PA`;
-- TRUNCATE TABLE `PRICE_ZONE_01`;

INSERT INTO `PA`
VALUES ('1000001', 1, 637.6, '2019-12-26 00:00:00', 1577232000, 'p');

INSERT INTO `PRICE_ZONE_01`
VALUES ('1000001', 1, '100001', '2019-12-26 00:00:00');
